module.exports = [
  {
    "kode": "BTK001",
    "slug": "parang-rusak",
    "nama": "Parang Rusak",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Parang",
    "warna_dominan": "cokelat sogan",
    "warna_sekunder": "krem",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Parang Rusak pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Parang Rusak merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Parang menggunakan warna dominan cokelat sogan dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK002",
    "slug": "parang-barong",
    "nama": "Parang Barong",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Parang",
    "warna_dominan": "cokelat tua",
    "warna_sekunder": "krem",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Parang Barong pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Parang Barong merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Parang menggunakan warna dominan cokelat tua dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK003",
    "slug": "parang-kusumo",
    "nama": "Parang Kusumo",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Parang",
    "warna_dominan": "cokelat sogan",
    "warna_sekunder": "putih",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Parang Kusumo pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Parang Kusumo merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Parang menggunakan warna dominan cokelat sogan dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK004",
    "slug": "kawung",
    "nama": "Kawung",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Kawung",
    "warna_dominan": "cokelat",
    "warna_sekunder": "putih",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Kawung pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Kawung merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Kawung menggunakan warna dominan cokelat dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK005",
    "slug": "truntum",
    "nama": "Truntum",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Bintang Truntum",
    "warna_dominan": "cokelat sogan",
    "warna_sekunder": "krem",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Truntum pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Truntum merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Bintang Truntum menggunakan warna dominan cokelat sogan dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK006",
    "slug": "sidomukti",
    "nama": "Sidomukti",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Sido",
    "warna_dominan": "cokelat",
    "warna_sekunder": "krem",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Sidomukti pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Sidomukti merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Sido menggunakan warna dominan cokelat dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK007",
    "slug": "sidoluhur",
    "nama": "Sidoluhur",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Sido",
    "warna_dominan": "cokelat tua",
    "warna_sekunder": "putih",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Sidoluhur pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Sidoluhur merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Sido menggunakan warna dominan cokelat tua dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK008",
    "slug": "sidoasih",
    "nama": "Sidoasih",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Sido",
    "warna_dominan": "cokelat sogan",
    "warna_sekunder": "putih",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Sidoasih pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Sidoasih merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Sido menggunakan warna dominan cokelat sogan dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK009",
    "slug": "semen-rama",
    "nama": "Semen Rama",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Flora Fauna",
    "motif_utama": "Semen",
    "warna_dominan": "cokelat",
    "warna_sekunder": "krem",
    "gaya_batik": "Keraton",
    "filosofi": "keanekaragaman dan keharmonisan kehidupan",
    "makna": "Motif Semen Rama pada dataset ini merepresentasikan keanekaragaman dan keharmonisan kehidupan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Semen Rama merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Semen menggunakan warna dominan cokelat dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK010",
    "slug": "sekar-jagad",
    "nama": "Sekar Jagad",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Sekar Jagad",
    "warna_dominan": "cokelat",
    "warna_sekunder": "biru",
    "gaya_batik": "Klasik",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Sekar Jagad pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Sekar Jagad merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Sekar Jagad menggunakan warna dominan cokelat dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK011",
    "slug": "nitik",
    "nama": "Nitik",
    "daerah": "Yogyakarta",
    "kota_asal": "Bantul",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Nitik",
    "warna_dominan": "cokelat tua",
    "warna_sekunder": "putih",
    "gaya_batik": "Klasik",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Nitik pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Nitik merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Nitik menggunakan warna dominan cokelat tua dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK012",
    "slug": "tambal",
    "nama": "Tambal",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Tambal",
    "warna_dominan": "cokelat",
    "warna_sekunder": "krem",
    "gaya_batik": "Klasik",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Tambal pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Tambal merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Tambal menggunakan warna dominan cokelat dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK013",
    "slug": "ceplok",
    "nama": "Ceplok",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Ceplok",
    "warna_dominan": "cokelat",
    "warna_sekunder": "putih",
    "gaya_batik": "Klasik",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Ceplok pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Cap",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Ceplok merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Ceplok menggunakan warna dominan cokelat dengan warna sekunder putih, serta dicatat menggunakan teknik Cap."
  },
  {
    "kode": "BTK014",
    "slug": "gurda",
    "nama": "Gurda",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Fauna",
    "motif_utama": "Garuda",
    "warna_dominan": "cokelat tua",
    "warna_sekunder": "emas",
    "gaya_batik": "Keraton",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Gurda pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "sutra",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Gurda merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Garuda menggunakan warna dominan cokelat tua dengan warna sekunder emas, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK015",
    "slug": "udan-liris",
    "nama": "Udan Liris",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Garis Diagonal",
    "warna_dominan": "cokelat sogan",
    "warna_sekunder": "putih",
    "gaya_batik": "Keraton",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Udan Liris pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Udan Liris merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Garis Diagonal menggunakan warna dominan cokelat sogan dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK016",
    "slug": "wahyu-tumurun",
    "nama": "Wahyu Tumurun",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Mahkota",
    "warna_dominan": "cokelat",
    "warna_sekunder": "krem",
    "gaya_batik": "Keraton",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Wahyu Tumurun pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Wahyu Tumurun merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Mahkota menggunakan warna dominan cokelat dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK017",
    "slug": "grompol",
    "nama": "Grompol",
    "daerah": "Yogyakarta",
    "kota_asal": "Kota Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Grompol",
    "warna_dominan": "cokelat sogan",
    "warna_sekunder": "putih",
    "gaya_batik": "Keraton",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Grompol pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Grompol merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Yogyakarta, DI Yogyakarta. Motif utama Grompol menggunakan warna dominan cokelat sogan dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK018",
    "slug": "slobog",
    "nama": "Slobog",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Kotak Diagonal",
    "warna_dominan": "cokelat tua",
    "warna_sekunder": "krem",
    "gaya_batik": "Klasik",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Slobog pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Slobog merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Kotak Diagonal menggunakan warna dominan cokelat tua dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK019",
    "slug": "pamiluto",
    "nama": "Pamiluto",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Pamiluto",
    "warna_dominan": "cokelat",
    "warna_sekunder": "putih",
    "gaya_batik": "Klasik",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Pamiluto pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Pamiluto merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Pamiluto menggunakan warna dominan cokelat dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK020",
    "slug": "babon-angrem",
    "nama": "Babon Angrem",
    "daerah": "Surakarta",
    "kota_asal": "Surakarta",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Fauna",
    "motif_utama": "Ayam",
    "warna_dominan": "cokelat sogan",
    "warna_sekunder": "krem",
    "gaya_batik": "Klasik",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Babon Angrem pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Babon Angrem merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Surakarta, Jawa Tengah. Motif utama Ayam menggunakan warna dominan cokelat sogan dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK021",
    "slug": "mega-mendung",
    "nama": "Mega Mendung",
    "daerah": "Cirebon",
    "kota_asal": "Cirebon",
    "provinsi": "Jawa Barat",
    "pulau": "Jawa",
    "kategori_motif": "Alam",
    "motif_utama": "Awan",
    "warna_dominan": "biru",
    "warna_sekunder": "merah",
    "gaya_batik": "Pesisir",
    "filosofi": "kedekatan manusia dengan unsur alam",
    "makna": "Motif Mega Mendung pada dataset ini merepresentasikan kedekatan manusia dengan unsur alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Mega Mendung merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Cirebon, Jawa Barat. Motif utama Awan menggunakan warna dominan biru dengan warna sekunder merah, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK022",
    "slug": "wadasan",
    "nama": "Wadasan",
    "daerah": "Cirebon",
    "kota_asal": "Cirebon",
    "provinsi": "Jawa Barat",
    "pulau": "Jawa",
    "kategori_motif": "Alam",
    "motif_utama": "Batu Karang",
    "warna_dominan": "cokelat",
    "warna_sekunder": "biru",
    "gaya_batik": "Pesisir",
    "filosofi": "kedekatan manusia dengan unsur alam",
    "makna": "Motif Wadasan pada dataset ini merepresentasikan kedekatan manusia dengan unsur alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Wadasan merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Cirebon, Jawa Barat. Motif utama Batu Karang menggunakan warna dominan cokelat dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK023",
    "slug": "singa-barong",
    "nama": "Singa Barong",
    "daerah": "Cirebon",
    "kota_asal": "Cirebon",
    "provinsi": "Jawa Barat",
    "pulau": "Jawa",
    "kategori_motif": "Fauna",
    "motif_utama": "Singa Barong",
    "warna_dominan": "merah",
    "warna_sekunder": "biru",
    "gaya_batik": "Pesisir",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Singa Barong pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Singa Barong merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Cirebon, Jawa Barat. Motif utama Singa Barong menggunakan warna dominan merah dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK024",
    "slug": "paksi-naga-liman",
    "nama": "Paksi Naga Liman",
    "daerah": "Cirebon",
    "kota_asal": "Cirebon",
    "provinsi": "Jawa Barat",
    "pulau": "Jawa",
    "kategori_motif": "Fauna Mitologis",
    "motif_utama": "Paksi Naga Liman",
    "warna_dominan": "biru tua",
    "warna_sekunder": "merah",
    "gaya_batik": "Pesisir",
    "filosofi": "kekuatan, perlindungan, dan imajinasi budaya",
    "makna": "Motif Paksi Naga Liman pada dataset ini merepresentasikan kekuatan, perlindungan, dan imajinasi budaya.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Paksi Naga Liman merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Cirebon, Jawa Barat. Motif utama Paksi Naga Liman menggunakan warna dominan biru tua dengan warna sekunder merah, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK025",
    "slug": "taman-arum",
    "nama": "Taman Arum",
    "daerah": "Cirebon",
    "kota_asal": "Cirebon",
    "provinsi": "Jawa Barat",
    "pulau": "Jawa",
    "kategori_motif": "Flora",
    "motif_utama": "Taman Bunga",
    "warna_dominan": "hijau",
    "warna_sekunder": "biru",
    "gaya_batik": "Pesisir",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Taman Arum pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Taman Arum merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Cirebon, Jawa Barat. Motif utama Taman Bunga menggunakan warna dominan hijau dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK026",
    "slug": "jlamprang",
    "nama": "Jlamprang",
    "daerah": "Pekalongan",
    "kota_asal": "Pekalongan",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Jlamprang",
    "warna_dominan": "merah",
    "warna_sekunder": "kuning",
    "gaya_batik": "Pesisir",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Jlamprang pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Cap",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Jlamprang merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Pekalongan, Jawa Tengah. Motif utama Jlamprang menggunakan warna dominan merah dengan warna sekunder kuning, serta dicatat menggunakan teknik Cap."
  },
  {
    "kode": "BTK027",
    "slug": "buketan",
    "nama": "Buketan",
    "daerah": "Pekalongan",
    "kota_asal": "Pekalongan",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora",
    "motif_utama": "Buket Bunga",
    "warna_dominan": "merah muda",
    "warna_sekunder": "hijau",
    "gaya_batik": "Pesisir",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Buketan pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Buketan merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Pekalongan, Jawa Tengah. Motif utama Buket Bunga menggunakan warna dominan merah muda dengan warna sekunder hijau, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK028",
    "slug": "liong",
    "nama": "Liong",
    "daerah": "Pekalongan",
    "kota_asal": "Pekalongan",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Fauna Mitologis",
    "motif_utama": "Naga",
    "warna_dominan": "merah",
    "warna_sekunder": "emas",
    "gaya_batik": "Pesisir",
    "filosofi": "kekuatan, perlindungan, dan imajinasi budaya",
    "makna": "Motif Liong pada dataset ini merepresentasikan kekuatan, perlindungan, dan imajinasi budaya.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "sutra",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Liong merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Pekalongan, Jawa Tengah. Motif utama Naga menggunakan warna dominan merah dengan warna sekunder emas, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK029",
    "slug": "tujuh-rupa",
    "nama": "Tujuh Rupa",
    "daerah": "Pekalongan",
    "kota_asal": "Pekalongan",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Fauna",
    "motif_utama": "Bunga dan Burung",
    "warna_dominan": "merah",
    "warna_sekunder": "hijau",
    "gaya_batik": "Pesisir",
    "filosofi": "keanekaragaman dan keharmonisan kehidupan",
    "makna": "Motif Tujuh Rupa pada dataset ini merepresentasikan keanekaragaman dan keharmonisan kehidupan.",
    "teknik_pembuatan": "Cap",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Tujuh Rupa merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Pekalongan, Jawa Tengah. Motif utama Bunga dan Burung menggunakan warna dominan merah dengan warna sekunder hijau, serta dicatat menggunakan teknik Cap."
  },
  {
    "kode": "BTK030",
    "slug": "terang-bulan",
    "nama": "Terang Bulan",
    "daerah": "Pekalongan",
    "kota_asal": "Pekalongan",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora",
    "motif_utama": "Bunga",
    "warna_dominan": "biru",
    "warna_sekunder": "putih",
    "gaya_batik": "Pesisir",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Terang Bulan pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": false,
    "deskripsi": "Terang Bulan merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Pekalongan, Jawa Tengah. Motif utama Bunga menggunakan warna dominan biru dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK031",
    "slug": "jawa-hokokai",
    "nama": "Jawa Hokokai",
    "daerah": "Pekalongan",
    "kota_asal": "Pekalongan",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Fauna",
    "motif_utama": "Bunga dan Kupu-kupu",
    "warna_dominan": "merah",
    "warna_sekunder": "kuning",
    "gaya_batik": "Pesisir",
    "filosofi": "keanekaragaman dan keharmonisan kehidupan",
    "makna": "Motif Jawa Hokokai pada dataset ini merepresentasikan keanekaragaman dan keharmonisan kehidupan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": false,
    "deskripsi": "Jawa Hokokai merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Pekalongan, Jawa Tengah. Motif utama Bunga dan Kupu-kupu menggunakan warna dominan merah dengan warna sekunder kuning, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK032",
    "slug": "lasem-tiga-negeri",
    "nama": "Lasem Tiga Negeri",
    "daerah": "Lasem",
    "kota_asal": "Rembang",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Tiga Negeri",
    "warna_dominan": "merah",
    "warna_sekunder": "biru",
    "gaya_batik": "Pesisir",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Lasem Tiga Negeri pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Lasem Tiga Negeri merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Lasem, Jawa Tengah. Motif utama Tiga Negeri menggunakan warna dominan merah dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK033",
    "slug": "latohan",
    "nama": "Latohan",
    "daerah": "Lasem",
    "kota_asal": "Rembang",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Laut",
    "motif_utama": "Latoh",
    "warna_dominan": "merah khas lasem",
    "warna_sekunder": "hijau",
    "gaya_batik": "Pesisir",
    "filosofi": "hubungan masyarakat pesisir dengan sumber daya laut",
    "makna": "Motif Latohan pada dataset ini merepresentasikan hubungan masyarakat pesisir dengan sumber daya laut.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Latohan merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Lasem, Jawa Tengah. Motif utama Latoh menggunakan warna dominan merah khas lasem dengan warna sekunder hijau, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK034",
    "slug": "sekar-jagad-lasem",
    "nama": "Sekar Jagad Lasem",
    "daerah": "Lasem",
    "kota_asal": "Rembang",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Sekar Jagad",
    "warna_dominan": "merah",
    "warna_sekunder": "biru",
    "gaya_batik": "Pesisir",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Sekar Jagad Lasem pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Sekar Jagad Lasem merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Lasem, Jawa Tengah. Motif utama Sekar Jagad menggunakan warna dominan merah dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK035",
    "slug": "burung-hong-lasem",
    "nama": "Burung Hong Lasem",
    "daerah": "Lasem",
    "kota_asal": "Rembang",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Fauna",
    "motif_utama": "Burung Hong",
    "warna_dominan": "merah",
    "warna_sekunder": "emas",
    "gaya_batik": "Pesisir",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Burung Hong Lasem pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "sutra",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Burung Hong Lasem merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Lasem, Jawa Tengah. Motif utama Burung Hong menggunakan warna dominan merah dengan warna sekunder emas, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK036",
    "slug": "lok-can-lasem",
    "nama": "Lok Can Lasem",
    "daerah": "Lasem",
    "kota_asal": "Rembang",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Fauna",
    "motif_utama": "Burung Phoenix",
    "warna_dominan": "merah",
    "warna_sekunder": "biru",
    "gaya_batik": "Pesisir",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Lok Can Lasem pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Lok Can Lasem merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Lasem, Jawa Tengah. Motif utama Burung Phoenix menggunakan warna dominan merah dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK037",
    "slug": "bakaran-gandrung",
    "nama": "Bakaran Gandrung",
    "daerah": "Juwana",
    "kota_asal": "Pati",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Gandrung",
    "warna_dominan": "hitam",
    "warna_sekunder": "cokelat",
    "gaya_batik": "Pesisir",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Bakaran Gandrung pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Bakaran Gandrung merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Juwana, Jawa Tengah. Motif utama Gandrung menggunakan warna dominan hitam dengan warna sekunder cokelat, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK038",
    "slug": "bakaran-blebak-kopik",
    "nama": "Bakaran Blebak Kopik",
    "daerah": "Juwana",
    "kota_asal": "Pati",
    "provinsi": "Jawa Tengah",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Blebak Kopik",
    "warna_dominan": "hitam",
    "warna_sekunder": "putih",
    "gaya_batik": "Pesisir",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Bakaran Blebak Kopik pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Bakaran Blebak Kopik merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Juwana, Jawa Tengah. Motif utama Blebak Kopik menggunakan warna dominan hitam dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK039",
    "slug": "gentongan",
    "nama": "Gentongan",
    "daerah": "Tanjung Bumi",
    "kota_asal": "Bangkalan",
    "provinsi": "Jawa Timur",
    "pulau": "Madura",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Gentongan",
    "warna_dominan": "merah",
    "warna_sekunder": "biru",
    "gaya_batik": "Pesisir",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Gentongan pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis Gentong",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Gentongan merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Tanjung Bumi, Jawa Timur. Motif utama Gentongan menggunakan warna dominan merah dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis Gentong."
  },
  {
    "kode": "BTK040",
    "slug": "sekar-jagad-madura",
    "nama": "Sekar Jagad Madura",
    "daerah": "Madura",
    "kota_asal": "Pamekasan",
    "provinsi": "Jawa Timur",
    "pulau": "Madura",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Sekar Jagad",
    "warna_dominan": "merah",
    "warna_sekunder": "kuning",
    "gaya_batik": "Pesisir",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Sekar Jagad Madura pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Sekar Jagad Madura merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Madura, Jawa Timur. Motif utama Sekar Jagad menggunakan warna dominan merah dengan warna sekunder kuning, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK041",
    "slug": "perahu-layar",
    "nama": "Perahu Layar",
    "daerah": "Madura",
    "kota_asal": "Pamekasan",
    "provinsi": "Jawa Timur",
    "pulau": "Madura",
    "kategori_motif": "Pesisir",
    "motif_utama": "Perahu",
    "warna_dominan": "biru",
    "warna_sekunder": "merah",
    "gaya_batik": "Pesisir",
    "filosofi": "kehidupan, perjalanan, dan dinamika masyarakat pesisir",
    "makna": "Motif Perahu Layar pada dataset ini merepresentasikan kehidupan, perjalanan, dan dinamika masyarakat pesisir.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Perahu Layar merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Madura, Jawa Timur. Motif utama Perahu menggunakan warna dominan biru dengan warna sekunder merah, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK042",
    "slug": "kembang-randu",
    "nama": "Kembang Randu",
    "daerah": "Madura",
    "kota_asal": "Sumenep",
    "provinsi": "Jawa Timur",
    "pulau": "Madura",
    "kategori_motif": "Flora",
    "motif_utama": "Bunga Randu",
    "warna_dominan": "merah",
    "warna_sekunder": "hijau",
    "gaya_batik": "Pesisir",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Kembang Randu pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Kembang Randu merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Madura, Jawa Timur. Motif utama Bunga Randu menggunakan warna dominan merah dengan warna sekunder hijau, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK043",
    "slug": "daun-memba",
    "nama": "Daun Memba",
    "daerah": "Madura",
    "kota_asal": "Sumenep",
    "provinsi": "Jawa Timur",
    "pulau": "Madura",
    "kategori_motif": "Flora",
    "motif_utama": "Daun",
    "warna_dominan": "hijau",
    "warna_sekunder": "merah",
    "gaya_batik": "Pesisir",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Daun Memba pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Daun Memba merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Madura, Jawa Timur. Motif utama Daun menggunakan warna dominan hijau dengan warna sekunder merah, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK044",
    "slug": "pring-sedapur",
    "nama": "Pring Sedapur",
    "daerah": "Magetan",
    "kota_asal": "Magetan",
    "provinsi": "Jawa Timur",
    "pulau": "Jawa",
    "kategori_motif": "Flora",
    "motif_utama": "Bambu",
    "warna_dominan": "hijau",
    "warna_sekunder": "cokelat",
    "gaya_batik": "Pedalaman",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Pring Sedapur pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Pring Sedapur merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Magetan, Jawa Timur. Motif utama Bambu menggunakan warna dominan hijau dengan warna sekunder cokelat, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK045",
    "slug": "gedog-kijing-miring",
    "nama": "Gedog Kijing Miring",
    "daerah": "Tuban",
    "kota_asal": "Tuban",
    "provinsi": "Jawa Timur",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Kijing Miring",
    "warna_dominan": "biru tua",
    "warna_sekunder": "putih",
    "gaya_batik": "Pesisir",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Gedog Kijing Miring pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis Gedog",
    "bahan_kain": "tenun gedog",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Gedog Kijing Miring merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Tuban, Jawa Timur. Motif utama Kijing Miring menggunakan warna dominan biru tua dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis Gedog."
  },
  {
    "kode": "BTK046",
    "slug": "gedog-panji-ori",
    "nama": "Gedog Panji Ori",
    "daerah": "Tuban",
    "kota_asal": "Tuban",
    "provinsi": "Jawa Timur",
    "pulau": "Jawa",
    "kategori_motif": "Flora Geometris",
    "motif_utama": "Panji Ori",
    "warna_dominan": "biru",
    "warna_sekunder": "cokelat",
    "gaya_batik": "Pesisir",
    "filosofi": "harmoni antara kehidupan, alam, dan keteraturan",
    "makna": "Motif Gedog Panji Ori pada dataset ini merepresentasikan harmoni antara kehidupan, alam, dan keteraturan.",
    "teknik_pembuatan": "Tulis Gedog",
    "bahan_kain": "tenun gedog",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Gedog Panji Ori merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Tuban, Jawa Timur. Motif utama Panji Ori menggunakan warna dominan biru dengan warna sekunder cokelat, serta dicatat menggunakan teknik Tulis Gedog."
  },
  {
    "kode": "BTK047",
    "slug": "gedog-ganggeng",
    "nama": "Gedog Ganggeng",
    "daerah": "Tuban",
    "kota_asal": "Tuban",
    "provinsi": "Jawa Timur",
    "pulau": "Jawa",
    "kategori_motif": "Flora Laut",
    "motif_utama": "Ganggeng",
    "warna_dominan": "biru tua",
    "warna_sekunder": "krem",
    "gaya_batik": "Pesisir",
    "filosofi": "hubungan masyarakat pesisir dengan sumber daya laut",
    "makna": "Motif Gedog Ganggeng pada dataset ini merepresentasikan hubungan masyarakat pesisir dengan sumber daya laut.",
    "teknik_pembuatan": "Tulis Gedog",
    "bahan_kain": "tenun gedog",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Gedog Ganggeng merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Tuban, Jawa Timur. Motif utama Ganggeng menggunakan warna dominan biru tua dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis Gedog."
  },
  {
    "kode": "BTK048",
    "slug": "besurek-rafflesia",
    "nama": "Besurek Rafflesia",
    "daerah": "Bengkulu",
    "kota_asal": "Bengkulu",
    "provinsi": "Bengkulu",
    "pulau": "Sumatra",
    "kategori_motif": "Flora",
    "motif_utama": "Rafflesia",
    "warna_dominan": "merah",
    "warna_sekunder": "hitam",
    "gaya_batik": "Tradisional",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Besurek Rafflesia pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Besurek Rafflesia merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Bengkulu, Bengkulu. Motif utama Rafflesia menggunakan warna dominan merah dengan warna sekunder hitam, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK049",
    "slug": "besurek-kaligrafi",
    "nama": "Besurek Kaligrafi",
    "daerah": "Bengkulu",
    "kota_asal": "Bengkulu",
    "provinsi": "Bengkulu",
    "pulau": "Sumatra",
    "kategori_motif": "Kaligrafi",
    "motif_utama": "Kaligrafi",
    "warna_dominan": "biru tua",
    "warna_sekunder": "emas",
    "gaya_batik": "Tradisional",
    "filosofi": "nilai spiritual dan penghormatan terhadap tradisi tulisan",
    "makna": "Motif Besurek Kaligrafi pada dataset ini merepresentasikan nilai spiritual dan penghormatan terhadap tradisi tulisan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Besurek Kaligrafi merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Bengkulu, Bengkulu. Motif utama Kaligrafi menggunakan warna dominan biru tua dengan warna sekunder emas, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK050",
    "slug": "besurek-burung-kuau",
    "nama": "Besurek Burung Kuau",
    "daerah": "Bengkulu",
    "kota_asal": "Bengkulu",
    "provinsi": "Bengkulu",
    "pulau": "Sumatra",
    "kategori_motif": "Fauna",
    "motif_utama": "Burung Kuau",
    "warna_dominan": "merah",
    "warna_sekunder": "hijau",
    "gaya_batik": "Tradisional",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Besurek Burung Kuau pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Besurek Burung Kuau merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Bengkulu, Bengkulu. Motif utama Burung Kuau menggunakan warna dominan merah dengan warna sekunder hijau, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK051",
    "slug": "durian-pecah",
    "nama": "Durian Pecah",
    "daerah": "Jambi",
    "kota_asal": "Kota Jambi",
    "provinsi": "Jambi",
    "pulau": "Sumatra",
    "kategori_motif": "Flora",
    "motif_utama": "Durian",
    "warna_dominan": "kuning",
    "warna_sekunder": "hijau",
    "gaya_batik": "Tradisional",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Durian Pecah pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Durian Pecah merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Jambi, Jambi. Motif utama Durian menggunakan warna dominan kuning dengan warna sekunder hijau, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK052",
    "slug": "angso-duo",
    "nama": "Angso Duo",
    "daerah": "Jambi",
    "kota_asal": "Kota Jambi",
    "provinsi": "Jambi",
    "pulau": "Sumatra",
    "kategori_motif": "Fauna",
    "motif_utama": "Angsa",
    "warna_dominan": "biru",
    "warna_sekunder": "putih",
    "gaya_batik": "Tradisional",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Angso Duo pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Angso Duo merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Jambi, Jambi. Motif utama Angsa menggunakan warna dominan biru dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK053",
    "slug": "kapal-sanggat",
    "nama": "Kapal Sanggat",
    "daerah": "Jambi",
    "kota_asal": "Kota Jambi",
    "provinsi": "Jambi",
    "pulau": "Sumatra",
    "kategori_motif": "Pesisir",
    "motif_utama": "Kapal",
    "warna_dominan": "biru tua",
    "warna_sekunder": "cokelat",
    "gaya_batik": "Tradisional",
    "filosofi": "kehidupan, perjalanan, dan dinamika masyarakat pesisir",
    "makna": "Motif Kapal Sanggat pada dataset ini merepresentasikan kehidupan, perjalanan, dan dinamika masyarakat pesisir.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Kapal Sanggat merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Jambi, Jambi. Motif utama Kapal menggunakan warna dominan biru tua dengan warna sekunder cokelat, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK054",
    "slug": "tampuk-manggis",
    "nama": "Tampuk Manggis",
    "daerah": "Jambi",
    "kota_asal": "Kota Jambi",
    "provinsi": "Jambi",
    "pulau": "Sumatra",
    "kategori_motif": "Flora",
    "motif_utama": "Manggis",
    "warna_dominan": "ungu",
    "warna_sekunder": "hijau",
    "gaya_batik": "Tradisional",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Tampuk Manggis pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Tampuk Manggis merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Jambi, Jambi. Motif utama Manggis menggunakan warna dominan ungu dengan warna sekunder hijau, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK055",
    "slug": "datulaya",
    "nama": "Datulaya",
    "daerah": "Banten",
    "kota_asal": "Serang",
    "provinsi": "Banten",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Datulaya",
    "warna_dominan": "cokelat",
    "warna_sekunder": "biru",
    "gaya_batik": "Kesultanan",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Datulaya pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Datulaya merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Banten, Banten. Motif utama Datulaya menggunakan warna dominan cokelat dengan warna sekunder biru, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK056",
    "slug": "pamaranggen",
    "nama": "Pamaranggen",
    "daerah": "Banten",
    "kota_asal": "Serang",
    "provinsi": "Banten",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Pamaranggen",
    "warna_dominan": "cokelat",
    "warna_sekunder": "krem",
    "gaya_batik": "Kesultanan",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Pamaranggen pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Pamaranggen merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Banten, Banten. Motif utama Pamaranggen menggunakan warna dominan cokelat dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK057",
    "slug": "kapurban",
    "nama": "Kapurban",
    "daerah": "Banten",
    "kota_asal": "Serang",
    "provinsi": "Banten",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Kapurban",
    "warna_dominan": "biru",
    "warna_sekunder": "cokelat",
    "gaya_batik": "Kesultanan",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Kapurban pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Kapurban merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Banten, Banten. Motif utama Kapurban menggunakan warna dominan biru dengan warna sekunder cokelat, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK058",
    "slug": "surosowan",
    "nama": "Surosowan",
    "daerah": "Banten",
    "kota_asal": "Serang",
    "provinsi": "Banten",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Surosowan",
    "warna_dominan": "cokelat",
    "warna_sekunder": "putih",
    "gaya_batik": "Kesultanan",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Surosowan pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Surosowan merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Banten, Banten. Motif utama Surosowan menggunakan warna dominan cokelat dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK059",
    "slug": "pancaniti",
    "nama": "Pancaniti",
    "daerah": "Banten",
    "kota_asal": "Serang",
    "provinsi": "Banten",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Pancaniti",
    "warna_dominan": "biru",
    "warna_sekunder": "krem",
    "gaya_batik": "Kesultanan",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Pancaniti pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Pancaniti merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Banten, Banten. Motif utama Pancaniti menggunakan warna dominan biru dengan warna sekunder krem, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK060",
    "slug": "ondel-ondel",
    "nama": "Ondel-Ondel",
    "daerah": "Betawi",
    "kota_asal": "Jakarta",
    "provinsi": "DKI Jakarta",
    "pulau": "Jawa",
    "kategori_motif": "Figuratif",
    "motif_utama": "Ondel-Ondel",
    "warna_dominan": "merah",
    "warna_sekunder": "kuning",
    "gaya_batik": "Betawi",
    "filosofi": "identitas budaya dan kehidupan masyarakat",
    "makna": "Motif Ondel-Ondel pada dataset ini merepresentasikan identitas budaya dan kehidupan masyarakat.",
    "teknik_pembuatan": "Cap",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 21,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Ondel-Ondel merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Betawi, DKI Jakarta. Motif utama Ondel-Ondel menggunakan warna dominan merah dengan warna sekunder kuning, serta dicatat menggunakan teknik Cap."
  },
  {
    "kode": "BTK061",
    "slug": "nusa-kelapa",
    "nama": "Nusa Kelapa",
    "daerah": "Betawi",
    "kota_asal": "Jakarta",
    "provinsi": "DKI Jakarta",
    "pulau": "Jawa",
    "kategori_motif": "Flora",
    "motif_utama": "Kelapa",
    "warna_dominan": "hijau",
    "warna_sekunder": "cokelat",
    "gaya_batik": "Betawi",
    "filosofi": "pertumbuhan, keindahan, dan hubungan manusia dengan alam",
    "makna": "Motif Nusa Kelapa pada dataset ini merepresentasikan pertumbuhan, keindahan, dan hubungan manusia dengan alam.",
    "teknik_pembuatan": "Cap",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 3,
    "penggunaan_tradisional": "acara adat",
    "is_warisan_tradisional": true,
    "deskripsi": "Nusa Kelapa merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Betawi, DKI Jakarta. Motif utama Kelapa menggunakan warna dominan hijau dengan warna sekunder cokelat, serta dicatat menggunakan teknik Cap."
  },
  {
    "kode": "BTK062",
    "slug": "ciliwung",
    "nama": "Ciliwung",
    "daerah": "Betawi",
    "kota_asal": "Jakarta",
    "provinsi": "DKI Jakarta",
    "pulau": "Jawa",
    "kategori_motif": "Alam",
    "motif_utama": "Sungai",
    "warna_dominan": "biru",
    "warna_sekunder": "hijau",
    "gaya_batik": "Betawi",
    "filosofi": "kedekatan manusia dengan unsur alam",
    "makna": "Motif Ciliwung pada dataset ini merepresentasikan kedekatan manusia dengan unsur alam.",
    "teknik_pembuatan": "Cap",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sedang",
    "estimasi_hari_pembuatan": 5,
    "penggunaan_tradisional": "busana formal",
    "is_warisan_tradisional": true,
    "deskripsi": "Ciliwung merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Betawi, DKI Jakarta. Motif utama Sungai menggunakan warna dominan biru dengan warna sekunder hijau, serta dicatat menggunakan teknik Cap."
  },
  {
    "kode": "BTK063",
    "slug": "salakanagara",
    "nama": "Salakanagara",
    "daerah": "Betawi",
    "kota_asal": "Jakarta",
    "provinsi": "DKI Jakarta",
    "pulau": "Jawa",
    "kategori_motif": "Historis",
    "motif_utama": "Salakanagara",
    "warna_dominan": "merah",
    "warna_sekunder": "cokelat",
    "gaya_batik": "Betawi",
    "filosofi": "ingatan kolektif dan identitas sejarah",
    "makna": "Motif Salakanagara pada dataset ini merepresentasikan ingatan kolektif dan identitas sejarah.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "rumit",
    "estimasi_hari_pembuatan": 7,
    "penggunaan_tradisional": "upacara keluarga",
    "is_warisan_tradisional": true,
    "deskripsi": "Salakanagara merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Betawi, DKI Jakarta. Motif utama Salakanagara menggunakan warna dominan merah dengan warna sekunder cokelat, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK064",
    "slug": "merak-ngibing",
    "nama": "Merak Ngibing",
    "daerah": "Garut",
    "kota_asal": "Garut",
    "provinsi": "Jawa Barat",
    "pulau": "Jawa",
    "kategori_motif": "Fauna",
    "motif_utama": "Merak",
    "warna_dominan": "biru",
    "warna_sekunder": "hijau",
    "gaya_batik": "Priangan",
    "filosofi": "karakter, keberanian, dan penghormatan terhadap makhluk hidup",
    "makna": "Motif Merak Ngibing pada dataset ini merepresentasikan karakter, keberanian, dan penghormatan terhadap makhluk hidup.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "sangat_rumit",
    "estimasi_hari_pembuatan": 10,
    "penggunaan_tradisional": "busana harian",
    "is_warisan_tradisional": true,
    "deskripsi": "Merak Ngibing merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Garut, Jawa Barat. Motif utama Merak menggunakan warna dominan biru dengan warna sekunder hijau, serta dicatat menggunakan teknik Tulis."
  },
  {
    "kode": "BTK065",
    "slug": "rereng-eneng",
    "nama": "Rereng Eneng",
    "daerah": "Ciamis",
    "kota_asal": "Ciamis",
    "provinsi": "Jawa Barat",
    "pulau": "Jawa",
    "kategori_motif": "Geometris",
    "motif_utama": "Rereng",
    "warna_dominan": "cokelat",
    "warna_sekunder": "putih",
    "gaya_batik": "Priangan",
    "filosofi": "keteraturan, keseimbangan, dan keteguhan",
    "makna": "Motif Rereng Eneng pada dataset ini merepresentasikan keteraturan, keseimbangan, dan keteguhan.",
    "teknik_pembuatan": "Tulis",
    "bahan_kain": "katun",
    "tingkat_kerumitan": "mudah",
    "estimasi_hari_pembuatan": 14,
    "penggunaan_tradisional": "dekorasi budaya",
    "is_warisan_tradisional": true,
    "deskripsi": "Rereng Eneng merupakan salah satu ragam motif batik yang pada dataset akademik ini dikaitkan dengan wilayah Ciamis, Jawa Barat. Motif utama Rereng menggunakan warna dominan cokelat dengan warna sekunder putih, serta dicatat menggunakan teknik Tulis."
  }
];
